@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cn.maxpixel.mods.randomsonnature.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;