@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cn.maxpixel.mods.randomsonnature.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;